// ===== DONNÉES DES BOUTIQUES PARTENAIRES =====
// Remplacez ces données fictives par les vraies informations

const boutiques = [
    {
        id: 9,
        name: "Arthus Bertrand",
        category: "mode",
        categoryLabel: "Mode",
        description: "Maison de joaillerie parisienne fondée en 1803, Arthus Bertrand perpétue un savoir-faire d'exception dans la création de bijoux, médailles et pièces d'orfèvrerie raffinées.",
        shortDesc: "Joaillerie parisienne depuis 1803",
        address: "Rue Bodenbroek 2-4, 1000 Bruxelles",
        hours: "Mar–Sam : 10h30–18h30",
        phone: "+32 2 503 65 55",
        mapUrl: "https://maps.google.com/?q=Arthus+Bertrand+Sablon+Bruxelles",
        website: "https://www.arthus-bertrand.com",
        instagram: "https://www.instagram.com/arthusbertrand",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80"
    },
    {
        id: 7,
        name: "Baobab Collection",
        category: "art-de-vivre",
        categoryLabel: "Art de vivre",
        description: "Maison belge fondée en 2002, Baobab Collection crée des bougies parfumées et diffuseurs d'exception soufflés à la main. Un art de vivre raffiné qui transforme chaque intérieur en écrin sensoriel.",
        shortDesc: "Bougies & parfums d'intérieur de luxe",
        address: "Rue des Sablons 15, 1000 Bruxelles",
        hours: "Lun–Sam : 10h30–18h30 · Dim : 11h–18h",
        phone: "+32 2 513 80 64",
        mapUrl: "https://maps.google.com/?q=Baobab+Collection+Sablon+Bruxelles",
        website: "https://www.baobabcollection.com",
        instagram: "https://www.instagram.com/baobabcollection",
        image: "https://eu.baobabcollection.com/cdn/shop/files/Sans_titre_363_x_342_px_204_x_401_px_2040_x_4010_px.png"
    },
    {
        id: 11,
        name: "Flamant",
        category: "art-de-vivre",
        categoryLabel: "Art de vivre",
        description: "Maison belge emblématique née au Sablon en 1972, Flamant incarne un art de vivre authentique : mobilier, luminaires et objets décoratifs aux matières nobles et aux lignes épurées.",
        shortDesc: "Mobilier & décoration d'intérieur",
        address: "Place du Grand Sablon 36, 1000 Bruxelles",
        hours: "Lun–Ven : 10h30–18h30 · Sam : 10h30–19h · Dim : 10h–18h",
        phone: "+32 2 514 47 07",
        mapUrl: "https://maps.google.com/?q=Flamant+Sablon+Bruxelles",
        website: "https://www.flamant.com",
        instagram: "https://www.instagram.com/flamant_official",
        image: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=800&q=80"
    },
    {
        id: 5,
        name: "Galerie Costermans",
        category: "art",
        categoryLabel: "Art & Culture",
        description: "Galerie d'art et d'antiquités établie depuis 1839. Spécialisée en mobilier, objets d'art et tableaux anciens dans un cadre somptueux au cœur du Sablon.",
        shortDesc: "Antiquités & art depuis 1839",
        address: "Place du Grand Sablon 5, 1000 Bruxelles",
        hours: "Mar–Sam : 10h–18h",
        phone: "+32 2 512 21 33",
        mapUrl: "https://maps.google.com/?q=Galerie+Costermans+Sablon+Bruxelles",
        website: "https://www.costermans-antiques.com",
        instagram: "",
        image: "https://images.costermans-antiques.com/magallery/CostermansMedia/SlidesShowMedia/marieschi-recadre-pr-site-260116-costermans-24962_2822026T13735.132.jpg"
    },
    {
        id: 8,
        name: "Gien",
        category: "art-de-vivre",
        categoryLabel: "Art de vivre",
        description: "Faïencerie française emblématique fondée en 1821, Gien propose des arts de la table et objets de décoration d'une élégance intemporelle, mêlant savoir-faire ancestral et créations contemporaines.",
        shortDesc: "Faïence française depuis 1821",
        address: "Rue des Sablons 1, 1000 Bruxelles",
        hours: "Mar–Dim : 10h30–18h30",
        phone: "+32 2 514 72 92",
        mapUrl: "https://maps.google.com/?q=Gien+Sablon+Bruxelles",
        website: "https://www.gien.com",
        instagram: "https://www.instagram.com/faiencerie_de_gien",
        image: "https://www.gien.com/cdn/shop/files/Boutique-03.jpg?v=1770720520&width=517"
    },
    {
        id: 6,
        name: "Le Pain Quotidien",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "L'enseigne bruxelloise iconique propose ses tartines généreuses, viennoiseries artisanales et brunchs bio dans un cadre chaleureux, à deux pas de l'hôtel.",
        shortDesc: "Tartines, brunch & bio — l'iconique belge",
        address: "Rue des Sablons 11, 1000 Bruxelles",
        hours: "Lun–Ven : 7h30–19h · Sam–Dim : 8h–19h",
        phone: "+32 2 513 51 54",
        mapUrl: "https://maps.google.com/?q=Le+Pain+Quotidien+Sablons+Bruxelles",
        website: "https://www.lepainquotidien.com",
        instagram: "https://www.instagram.com/lepainquotidien",
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80"
    },
    {
        id: 1,
        name: "Maison Marcolini",
        category: "chocolat",
        categoryLabel: "Chocolat",
        description: "Pierre Marcolini, chocolatier de renommée mondiale, propose des créations d'exception alliant savoir-faire belge et ingrédients sourcés directement auprès des producteurs de cacao.",
        shortDesc: "Haute chocolaterie belge d'exception",
        address: "Rue des Minimes 1, 1000 Bruxelles",
        hours: "Lun–Jeu : 10h–19h · Ven–Sam : 10h–19h30 · Dim : 10h–19h",
        phone: "+32 2 514 12 06",
        mapUrl: "https://maps.google.com/?q=Maison+Marcolini+Sablon+Bruxelles",
        website: "https://www.marcolini.com",
        instagram: "https://www.instagram.com/pierremarcolini",
        image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&q=80"
    },
    {
        id: 10,
        name: "Passion Chocolat",
        category: "chocolat",
        categoryLabel: "Chocolat",
        description: "Chocolaterie artisanale bruxelloise où chaque praline est élaborée dans la tradition belge. Une sélection gourmande de tablettes, ganaches et créations saisonnières à déguster sans modération.",
        shortDesc: "Chocolaterie artisanale bruxelloise",
        address: "Rue Bodenbroek 2/4, 1000 Bruxelles",
        hours: "Mar–Sam : 11h–19h · Dim : 11h–18h",
        phone: "+32 2 514 77 14",
        mapUrl: "https://maps.google.com/?q=Passion+Chocolat+Sablon+Bruxelles",
        website: "https://www.passionchocolat.be",
        instagram: "https://www.instagram.com/passionchocolatbrussels",
        image: "https://www.passionchocolat.be/sites/www.passionchocolat2.be/files/styles/hd/public/uploads/PC%20-%20Sablon%20-%2024.jpg.webp"
    },
    {
        id: 2,
        name: "Wittamer",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "Depuis 1910, la Maison Wittamer est une institution bruxelloise réputée pour ses pâtisseries raffinées, ses chocolats artisanaux et son salon de thé élégant au cœur du Sablon.",
        shortDesc: "Pâtisserie de prestige depuis 1910",
        address: "Place du Grand Sablon 12, 1000 Bruxelles",
        hours: "Lun : 8h30–17h30 · Mar–Ven : 7h30–18h30 · Sam–Dim : 7h–18h30",
        phone: "+32 2 318 16 22",
        mapUrl: "https://maps.google.com/?q=Wittamer+Grand+Sablon+Bruxelles",
        website: "https://www.wittamer.com",
        instagram: "https://www.instagram.com/wittamer_brussels",
        image: "https://wittamer.com/wp-content/uploads/2023/04/Sablon_WITTAMER-col.jpg"
    }
];
