// ===== DONNÉES DES BOUTIQUES PARTENAIRES =====
// Remplacez ces données fictives par les vraies informations

const boutiques = [
    {
        id: 18,
        name: "À la Bonne Heure",
        category: "joaillerie",
        categoryLabel: "Joaillerie",
        description: "Joaillier-horloger bruxellois installé au cœur du Sablon, À la Bonne Heure propose une sélection pointue de bijoux et de montres de créateurs, alliant conseil personnalisé et savoir-faire de proximité.",
        shortDesc: "Joaillier & horloger du Sablon",
        address: "Rue Bodenbroek 2A, 1000 Bruxelles",
        hours: "Mar–Ven : 10h30–18h · Sam : 10h30–18h30",
        phone: "+32 2 502 42 06",
        mapUrl: "https://maps.google.com/?q=A+la+Bonne+Heure+Bodenbroek+Sablon+Bruxelles",
        website: "https://alabonneheure-bruxelles.be",
        instagram: "",
        image: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&q=80"
    },
    {
        id: 16,
        name: "AMI Paris",
        category: "mode",
        categoryLabel: "Mode",
        description: "Fondée par Alexandre Mattiussi en 2011, AMI Paris incarne un vestiaire parisien chic et décontracté. Premier flagship belge de la maison, la boutique du Sablon réunit les collections femme et homme signées du célèbre « Ami de Cœur ».",
        shortDesc: "Mode parisienne chic & décontractée",
        address: "Place du Grand Sablon 5, 1000 Bruxelles",
        hours: "Lun–Sam : 10h–18h30",
        phone: "",
        mapUrl: "https://maps.google.com/?q=AMI+Paris+Grand+Sablon+Bruxelles",
        website: "https://www.amiparis.com",
        instagram: "https://www.instagram.com/amiparis",
        image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80"
    },
    {
        id: 9,
        name: "Arthus Bertrand",
        category: "joaillerie",
        categoryLabel: "Joaillerie",
        description: "Maison de joaillerie parisienne fondée en 1803, Arthus Bertrand perpétue un savoir-faire d'exception dans la création de bijoux, médailles et pièces d'orfèvrerie raffinées.",
        shortDesc: "Joaillerie parisienne depuis 1803",
        address: "Rue Bodenbroek 2-4, 1000 Bruxelles",
        hours: "Mar–Sam : 10h30–18h30",
        phone: "+32 2 503 65 55",
        mapUrl: "https://maps.google.com/?q=Arthus+Bertrand+Sablon+Bruxelles",
        website: "https://www.arthus-bertrand.com",
        instagram: "https://www.instagram.com/arthusbertrand",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80"
    },
    {
        id: 7,
        name: "Baobab Collection",
        category: "art-de-vivre",
        categoryLabel: "Art de vivre",
        description: "Maison belge fondée en 2002, Baobab Collection crée des bougies parfumées et diffuseurs d'exception soufflés à la main. Un art de vivre raffiné qui transforme chaque intérieur en écrin sensoriel.",
        shortDesc: "Bougies & parfums d'intérieur de luxe",
        address: "Rue des Sablons 15, 1000 Bruxelles",
        hours: "Lun–Sam : 10h30–18h30 · Dim : 11h–18h",
        phone: "+32 2 513 80 64",
        mapUrl: "https://maps.google.com/?q=Baobab+Collection+Sablon+Bruxelles",
        website: "https://www.baobabcollection.com",
        instagram: "https://www.instagram.com/baobabcollection",
        image: "https://eu.baobabcollection.com/cdn/shop/files/Sans_titre_363_x_342_px_204_x_401_px_2040_x_4010_px.png"
    },
    {
        id: 14,
        name: "Breitling",
        category: "horlogerie",
        categoryLabel: "Horlogerie",
        description: "Maison horlogère suisse fondée en 1884, Breitling est la référence des montres de l'aéronautique et des instruments pour professionnels. La boutique du Sablon réunit les collections iconiques Navitimer, Premier et Superocean.",
        shortDesc: "Montres-instruments suisses depuis 1884",
        address: "Place du Grand Sablon 8, 1000 Bruxelles",
        hours: "Lun–Ven : 10h30–18h · Sam : 10h30–18h30",
        phone: "+32 2 524 57 44",
        mapUrl: "https://maps.google.com/?q=Breitling+Boutique+Grand+Sablon+Bruxelles",
        website: "https://www.breitling.com",
        instagram: "https://www.instagram.com/breitling",
        image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=800&q=80"
    },
    {
        id: 21,
        name: "Chez Richard",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "Institution conviviale nichée au pied du Sablon, Chez Richard séduit par son ambiance vivante, sa terrasse prisée et sa cuisine de bistrot servie midi et soir dans un esprit chaleureux.",
        shortDesc: "Bar & cuisine de bistrot au Sablon",
        address: "Rue des Minimes 2, 1000 Bruxelles",
        hours: "Tous les jours : 11h30–minuit · Cuisine : 12h–15h · 17h30–22h",
        phone: "+32 479 61 12 56",
        mapUrl: "https://maps.google.com/?q=Chez+Richard+Minimes+Sablon+Bruxelles",
        website: "https://www.chezrichard.be",
        instagram: "",
        image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80"
    },
    {
        id: 15,
        name: "Christian Louboutin",
        category: "mode",
        categoryLabel: "Mode",
        description: "Créateur français mondialement reconnu pour ses souliers à la semelle rouge, Christian Louboutin sublime une élégance audacieuse. La boutique du Sablon présente souliers, maroquinerie et accessoires pour femme et homme.",
        shortDesc: "Souliers & maroquinerie à la semelle rouge",
        address: "Place du Grand Sablon 21, 1000 Bruxelles",
        hours: "Lun–Sam : 10h–18h30",
        phone: "+32 2 502 49 19",
        mapUrl: "https://maps.google.com/?q=Christian+Louboutin+Grand+Sablon+Bruxelles",
        website: "https://eu.christianlouboutin.com",
        instagram: "https://www.instagram.com/louboutinworld",
        image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80"
    },
    {
        id: 17,
        name: "dinh van",
        category: "joaillerie",
        categoryLabel: "Joaillerie",
        description: "Pionnier de la joaillerie contemporaine depuis 1965, dinh van réinvente le bijou avec des lignes épurées et un esprit libre. La boutique du Sablon présente les collections iconiques Menottes, Le Cube et Spirale.",
        shortDesc: "Joaillerie contemporaine depuis 1965",
        address: "Place du Grand Sablon 6, 1000 Bruxelles",
        hours: "Lun–Jeu : 10h30–18h30 · Sam : 10h–18h30",
        phone: "+32 2 511 83 53",
        mapUrl: "https://maps.google.com/?q=dinh+van+Grand+Sablon+Bruxelles",
        website: "https://www.dinhvan.com",
        instagram: "https://www.instagram.com/dinhvanofficiel",
        image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80"
    },
    {
        id: 11,
        name: "Flamant",
        category: "art-de-vivre",
        categoryLabel: "Art de vivre",
        description: "Maison belge emblématique née au Sablon en 1972, Flamant incarne un art de vivre authentique : mobilier, luminaires et objets décoratifs aux matières nobles et aux lignes épurées.",
        shortDesc: "Mobilier & décoration d'intérieur",
        address: "Place du Grand Sablon 36, 1000 Bruxelles",
        hours: "Lun–Ven : 10h30–18h30 · Sam : 10h30–19h · Dim : 10h–18h",
        phone: "+32 2 514 47 07",
        mapUrl: "https://maps.google.com/?q=Flamant+Sablon+Bruxelles",
        website: "https://www.flamant.com",
        instagram: "https://www.instagram.com/flamant_official",
        image: "https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=800&q=80"
    },
    {
        id: 5,
        name: "Galerie Costermans",
        category: "art",
        categoryLabel: "Art & Culture",
        description: "Galerie d'art et d'antiquités établie depuis 1839. Spécialisée en mobilier, objets d'art et tableaux anciens dans un cadre somptueux au cœur du Sablon.",
        shortDesc: "Antiquités & art depuis 1839",
        address: "Place du Grand Sablon 5, 1000 Bruxelles",
        hours: "Mar–Sam : 10h–18h",
        phone: "+32 2 512 21 33",
        mapUrl: "https://maps.google.com/?q=Galerie+Costermans+Sablon+Bruxelles",
        website: "https://www.costermans-antiques.com",
        instagram: "",
        image: "https://images.costermans-antiques.com/magallery/CostermansMedia/SlidesShowMedia/marieschi-recadre-pr-site-260116-costermans-24962_2822026T13735.132.jpg"
    },
    {
        id: 8,
        name: "Gien",
        category: "art-de-vivre",
        categoryLabel: "Art de vivre",
        description: "Faïencerie française emblématique fondée en 1821, Gien propose des arts de la table et objets de décoration d'une élégance intemporelle, mêlant savoir-faire ancestral et créations contemporaines.",
        shortDesc: "Faïence française depuis 1821",
        address: "Rue des Sablons 1, 1000 Bruxelles",
        hours: "Mar–Dim : 10h30–18h30",
        phone: "+32 2 514 72 92",
        mapUrl: "https://maps.google.com/?q=Gien+Sablon+Bruxelles",
        website: "https://www.gien.com",
        instagram: "https://www.instagram.com/faiencerie_de_gien",
        image: "https://www.gien.com/cdn/shop/files/Boutique-03.jpg?v=1770720520&width=517"
    },
    {
        id: 13,
        name: "IWC Schaffhausen",
        category: "horlogerie",
        categoryLabel: "Horlogerie",
        description: "Fondée à Schaffhouse en 1868, IWC Schaffhausen conjugue ingénierie horlogère suisse et design intemporel. La boutique bruxelloise dévoile les montres d'aviateur, Portugieser et Portofino dans un écrin raffiné.",
        shortDesc: "Manufacture horlogère suisse depuis 1868",
        address: "Place du Grand Sablon 10, 1000 Bruxelles",
        hours: "Lun–Sam : 10h30–18h30",
        phone: "+32 2 300 74 14",
        mapUrl: "https://maps.google.com/?q=IWC+Schaffhausen+Grand+Sablon+Bruxelles",
        website: "https://www.iwc.com",
        instagram: "https://www.instagram.com/iwcwatches",
        image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&q=80"
    },
    {
        id: 6,
        name: "Le Pain Quotidien",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "L'enseigne bruxelloise iconique propose ses tartines généreuses, viennoiseries artisanales et brunchs bio dans un cadre chaleureux, à deux pas de l'hôtel.",
        shortDesc: "Tartines, brunch & bio — l'iconique belge",
        address: "Rue des Sablons 11, 1000 Bruxelles",
        hours: "Lun–Ven : 7h30–19h · Sam–Dim : 8h–19h",
        phone: "+32 2 513 51 54",
        mapUrl: "https://maps.google.com/?q=Le+Pain+Quotidien+Sablons+Bruxelles",
        website: "https://www.lepainquotidien.com",
        instagram: "https://www.instagram.com/lepainquotidien",
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80"
    },
    {
        id: 20,
        name: "Lola",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "Brasserie contemporaine emblématique du Grand Sablon depuis plus de 25 ans, Lola propose une cuisine de marché généreuse dans une ambiance conviviale et chaleureuse, à deux pas de l'hôtel.",
        shortDesc: "Brasserie contemporaine du Sablon",
        address: "Place du Grand Sablon 33, 1000 Bruxelles",
        hours: "Lun–Jeu : 12h–14h30 · 18h30–22h30 · Ven : jusqu'à 23h · Sam : 12h–23h · Dim : 12h–22h",
        phone: "+32 2 514 24 60",
        mapUrl: "https://maps.google.com/?q=Lola+Restaurant+Grand+Sablon+Bruxelles",
        website: "https://www.lola-restaurant.be",
        instagram: "",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80"
    },
    {
        id: 1,
        name: "Maison Marcolini",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "Pierre Marcolini, chocolatier de renommée mondiale, propose des créations d'exception alliant savoir-faire belge et ingrédients sourcés directement auprès des producteurs de cacao.",
        shortDesc: "Haute chocolaterie belge d'exception",
        address: "Rue des Minimes 1, 1000 Bruxelles",
        hours: "Lun–Jeu : 10h–19h · Ven–Sam : 10h–19h30 · Dim : 10h–19h",
        phone: "+32 2 514 12 06",
        mapUrl: "https://maps.google.com/?q=Maison+Marcolini+Sablon+Bruxelles",
        website: "https://www.marcolini.com",
        instagram: "https://www.instagram.com/pierremarcolini",
        image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&q=80"
    },
    {
        id: 19,
        name: "Messika",
        category: "joaillerie",
        categoryLabel: "Joaillerie",
        description: "Maison de haute joaillerie parisienne fondée par Valérie Messika en 2005, célèbre pour ses diamants en mouvement et son style audacieux. La boutique du Sablon dévoile les collections Move, Lucky Move et les créations couture.",
        shortDesc: "Haute joaillerie du diamant depuis 2005",
        address: "Place du Grand Sablon 20, 1000 Bruxelles",
        hours: "Lun–Sam : 10h30–13h · 13h30–18h30",
        phone: "+32 2 669 88 80",
        mapUrl: "https://maps.google.com/?q=Messika+Boutique+Grand+Sablon+Bruxelles",
        website: "https://www.messika.com",
        instagram: "https://www.instagram.com/messikajewelry",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80"
    },
    {
        id: 10,
        name: "Passion Chocolat",
        category: "chocolat",
        categoryLabel: "Chocolat",
        description: "Chocolaterie artisanale bruxelloise où chaque praline est élaborée dans la tradition belge. Une sélection gourmande de tablettes, ganaches et créations saisonnières à déguster sans modération.",
        shortDesc: "Chocolaterie artisanale bruxelloise",
        address: "Rue Bodenbroek 2/4, 1000 Bruxelles",
        hours: "Mar–Sam : 11h–19h · Dim : 11h–18h",
        phone: "+32 2 514 77 14",
        mapUrl: "https://maps.google.com/?q=Passion+Chocolat+Sablon+Bruxelles",
        website: "https://www.passionchocolat.be",
        instagram: "https://www.instagram.com/passionchocolatbrussels",
        image: "https://www.passionchocolat.be/sites/www.passionchocolat2.be/files/styles/hd/public/uploads/PC%20-%20Sablon%20-%2024.jpg.webp"
    },
    {
        id: 12,
        name: "TAG Heuer",
        category: "horlogerie",
        categoryLabel: "Horlogerie",
        description: "Manufacture horlogère suisse fondée en 1860, TAG Heuer incarne l'avant-garde et la précision au service du sport automobile. La boutique du Sablon présente les collections iconiques Carrera, Monaco et Aquaracer.",
        shortDesc: "Horlogerie suisse d'avant-garde depuis 1860",
        address: "Place du Grand Sablon 19, 1000 Bruxelles",
        hours: "Lun–Sam : 10h30–13h · 13h30–18h30",
        phone: "+32 2 369 22 22",
        mapUrl: "https://maps.google.com/?q=TAG+Heuer+Boutique+Grand+Sablon+Bruxelles",
        website: "https://www.tagheuer.com",
        instagram: "https://www.instagram.com/tagheuer",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80"
    },
    {
        id: 2,
        name: "Wittamer",
        category: "restauration",
        categoryLabel: "Restauration",
        description: "Depuis 1910, la Maison Wittamer est une institution bruxelloise réputée pour ses pâtisseries raffinées, ses chocolats artisanaux et son salon de thé élégant au cœur du Sablon.",
        shortDesc: "Pâtisserie de prestige depuis 1910",
        address: "Place du Grand Sablon 12, 1000 Bruxelles",
        hours: "Lun : 8h30–17h30 · Mar–Ven : 7h30–18h30 · Sam–Dim : 7h–18h30",
        phone: "+32 2 318 16 22",
        mapUrl: "https://maps.google.com/?q=Wittamer+Grand+Sablon+Bruxelles",
        website: "https://www.wittamer.com",
        instagram: "https://www.instagram.com/wittamer_brussels",
        image: "https://wittamer.com/wp-content/uploads/2023/04/Sablon_WITTAMER-col.jpg"
    }
];